---
- hosts: dev
  become: true
  tasks:
    - name: Install python pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker
      apt:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: Start the Container
      docker_container:
        name: myweb
        image: mlogu6/myweb:{{ DOCKER_TAG }}
        state: started
        published_ports:
          - 0.0.0.0:8086:8080
